### ISSUE TITLE
failed to decrypt notes: failed to decrypt: failed to decrypt encrypted secret: invalid mac

### ISSUE THREAD

**Issue by kucharskim** [doy/rbw#200]
This started recently. Not sure did is my config damaged somehow? It was working without any problems for months.

```
$ jq -r . < .config/rbw/config.json  
{
  "email": "<REDACTED>",
  "base_url": null,
  "identity_url": null,
  "notifications_url": null,
  "lock_timeout": 3600,
  "sync_interval": 3600,
  "pinentry": "pinentry",
  "client_cert_path": null
}
 ```
 
 ```
 $ rbw list | wc -l 
WARN: failed to decrypt notes: failed to decrypt: failed to decrypt encrypted secret: invalid mac
WARN: failed to decrypt username: failed to decrypt: failed to decrypt encrypted secret: invalid mac
WARN: failed to decrypt password: failed to decrypt: failed to decrypt encrypted secret: invalid mac
WARN: failed to decrypt totp: failed to decrypt: failed to decrypt encrypted secret: invalid mac
rbw list: failed to decrypt: failed to decrypt encrypted secret: invalid mac
       0
```

```
$ rbw --version 
rbw 1.11.1
```

**Comment by kucharskim** [comment]
```
$ ls -lhn .cache/rbw/default:mikolaj@chorus.one.json
-rw-r-----  1 5001  5001   134K Aug 13 21:02 .cache/rbw/default:<REDACTED>.json

$ jq -Mr . < .cache/rbw/default:mikolaj@chorus.one.json > /dev/null                                               
$ echo $?
0
```

**Comment by sedlund** [comment]
[1.12.1](https://github.com/doy/rbw/releases/tag/1.12.1) [Latest](https://github.com/doy/rbw/releases/latest)
[1.12.1] - 2024-07-28
Fixed
Fix decrypting folder names of entries with individual item encryption keys

**Comment by dehoej** [comment]
I am using Pop_OS 22.04 with rbw 1.12.1 and i still have this issue. I am using vaultwarden.

**Comment by sedlund** [comment]
Did you try rbw purge

**Comment by dehoej** [comment]
Yes i did.

**Comment by dehoej** [comment]
Also tried to delete the folders.

**Comment by sedlund** [comment]
What is the output of rbw --version ? 

Did you reboot? 

What is the command and error?

**Comment by dehoej** [comment]
```
rbw --version
rbw 1.12.1
```

I also tried to reboot.

```
dehoej@p14s-pop:~$ rbw list
rbw list: failed to decrypt: failed to decrypt encrypted secret: invalid mac
```

**Comment by sedlund** [comment]
did you try this:

*NOTE: If you were affected by issue #163 (getting messages like `failed to
decrypt encrypted secret: invalid mac` when doing any operations on your
vault), you will need to `rbw sync` after upgrading in order to update your
local vault with the necessary new data.*

**Comment by dehoej** [comment]
Yes i also did that.

**Comment by sedlund** [comment]
I think your vaultwarden is old

**Comment by dehoej** [comment]
I am running the latest version of vaultwarden: 1.32.0
and web is 2024.6.2b

**Comment by kucharskim** [comment]
I've opened this issue and finally managed to test `1.12.1` and it fixes the problem for me with official https://vault.bitwarden.com/ backend. All works. Thanks!

**Comment by sedlund** [comment]
good update!  you can close.
